config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  devise_for :users

  namespace :admin do
    resources :products
    resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end




  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :reviews
  end



  resources :favorites

resources :carts do
  collection do
    delete :clean
    post :checkout
  end
end

namespace :account do
  resources :orders
end

  resources :orders do
    member do
     post :pay_with_alipay
     post :pay_with_wechat
     post :apply_to_cancel
    end
  end






    resources :cart_items
    resources :orders
    resources :products_mu
    resources :products_ci
    resources :products_shi
    resources :protfolio

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product



    def add_product_to_cart(product)
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
      ci.save
    end


def total_price
  sum = 0
  cart_items.each do |cart_item|
    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end
  end
  sum
end


def clean!
  cart_items.destroy_all
end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :product_lists
    before_create :generate_token

    def generate_token
      self.token = SecureRandom.uuid
    end

   def set_payment_with!(method)
    self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  include AASM

  aasm do
   state :order_placed, initial: true
   state :paid
   state :shipping
   state :shipped
   state :order_cancelled
   state :good_returned


  event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
  end

  event :ship do
    transitions from: :paid,         to: :shipping
  end

  event :deliver do
    transitions from: :shipping,     to: :shipped
  end

  event :return_good do
    transitions from: :shipped,      to: :good_returned
  end

  event :cancell_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
  end
end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  ratyrate_rateable "a", "b", "c"

  has_many :reviews

  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user

end

app/models/product_ci.rb
class ProductCi < ApplicationRecord

has_many :reviews

end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/product_mu.rb
class ProductMu < ApplicationRecord

has_many :reviews

end

app/models/product_shi.rb
class ProductShi < ApplicationRecord

has_many :reviews

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :product
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :favorites
  has_many :favorite_products, :through => :favorites, :source => :product
  
  def is_fan_of?(group)
   favorite_products.include?(group)
  end

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  ratyrate_rater

  def admin?
    is_admin
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :authenticate_user!, only: [:checkout]

  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

    def checkout
      @order = Order.new
    end

end

app/helpers/carts_helper.rb
module CartsHelper

def render_cart_total_price(cart)

  cart.total_price
end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
 def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/checkout.html.erb
<style media="screen">
.ck{
  padding: 50px;
  padding-left: 55px;
  padding-right: 55px;
}
.row{

}
</style>


<div class="row checkoutevey">
   <div class="col-md-12 ck">

    <h2> 购物明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>

            <td>
              <%= cart_item.quantity %>
            </td>

          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= render_cart_total_price(current_cart) %> CNY
      </span>
    </div>

    <hr>

    <h2> 订单资讯 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>



          <legend> 订购人</legend>
          <div class="form-group col-lg-6">
            <%= f.input :billing_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :billing_address  %>
          </div>

          <legend> 收货人</legend>
          <div class="form-group col-lg-6">
           <%= f.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :shipping_address  %>
          </div>

        <div class="checkout">
          <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<style media="screen">
  .carts-evey{
    padding-top: 20px;
    padding-left: 40px;
    padding-right: 40px;
    padding-bottom: 20px;
    //background-color: #edeeed;
    background-color: #302f2f;
    background-size: cover;
    background-image: url("https://static.pexels.com/photos/5106/forest-trees-fog-foggy.jpg");
    background-size: cover;
  }
  a{
    color: black;
    font-weight: bold;
  }
  .bgc{
    //background-color: rgba(255,255,255,0.2);
    border-radius: 3px;
  }
  .body{
    padding-top: 20px;
    padding-left: 40px;
    padding-right: 40px;
    width: 90%;
  }
  .table{
    //background-color: white;
  }
  thead{
    //background-color: #b10000;
    //background-image: url("http://pic44.nipic.com/20140725/11235789_094547908000_2.jpg");
    //color:white;
    text-align: center;

  }
  table{
    padding: 30px;

  }
</style>

<body>


<div class="row carts-evey checkout">
  <div class="col-md-12 bgc">

<%= link_to("清空购物车", clean_carts_path, method: :delete, class: "pull-right btn btn-danger", style:"", data: {confirm:"你确定要清空整个购物车吗？"}) %>

    <h2 style="color:#3c3837;">购物车</h2>
<hr>
<table class="table table-bordered">

<thead>
  <tr>
    <th colspan="2">商品资讯</th>
    <th>单价</th>
    <th>数量</th>
    <th>操作选项</th>
  </tr>
</thead>

<tbody>
<% current_cart.cart_items.each do |cart_item| %>
<tr>
  <td>
<%= link_to product_path(cart_item.product) do %>
<% if cart_item.product.image.present? %>
<%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
<% else %>
<%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
<% end %>
<% end %>

  </td>
  <td>
<%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
  </td>

  <td>
<%= cart_item.product.price %>
  </td>

  <td>

<% cart_item = current_cart.cart_items.find_by(product_id: cart_item.product_id) %>
<%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
 <%= f.select :quantity, 1..cart_item.product.quantity %>
<%= f.submit "更新",class:"btn btn-info",style:"width:60px;", data: {disable_with: "Submiting..."} %>
<% end %>
  </td>

  <td>
             <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
                <i class="fa fa-trash fa-lg"></i>
              <% end %>
  </td>



</tr>
<% end %>

</tbody>

</table>

<br>
<div class="total clearfix">
  <span class="pull-right">
    <span>

总计<%= render_cart_total_price(current_cart) %>RMB



    </span>
  </span>

</div>

<hr>

<div class="checkout clearfix">
  <%= link_to("确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right")%>

</div>
  </div>
</div>
</body>