config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  devise_for :users

  namespace :admin do
    resources :products
    resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end




  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :reviews
  end



  resources :favorites

resources :carts do
  collection do
    delete :clean
    post :checkout
  end
end

namespace :account do
  resources :orders
end

  resources :orders do
    member do
     post :pay_with_alipay
     post :pay_with_wechat
     post :apply_to_cancel
    end
  end






    resources :cart_items
    resources :orders
    resources :products_mu
    resources :products_ci
    resources :products_shi
    resources :protfolio

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product



    def add_product_to_cart(product)
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
      ci.save
    end


def total_price
  sum = 0
  cart_items.each do |cart_item|
    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end
  end
  sum
end


def clean!
  cart_items.destroy_all
end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :product_lists
    before_create :generate_token

    def generate_token
      self.token = SecureRandom.uuid
    end

   def set_payment_with!(method)
    self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  include AASM

  aasm do
   state :order_placed, initial: true
   state :paid
   state :shipping
   state :shipped
   state :order_cancelled
   state :good_returned


  event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
  end

  event :ship do
    transitions from: :paid,         to: :shipping
  end

  event :deliver do
    transitions from: :shipping,     to: :shipped
  end

  event :return_good do
    transitions from: :shipped,      to: :good_returned
  end

  event :cancell_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
  end
end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  ratyrate_rateable "a", "b", "c"

  has_many :reviews

  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user

end

app/models/product_ci.rb
class ProductCi < ApplicationRecord

has_many :reviews

end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/product_mu.rb
class ProductMu < ApplicationRecord

has_many :reviews

end

app/models/product_shi.rb
class ProductShi < ApplicationRecord

has_many :reviews

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :product
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :favorites
  has_many :favorite_products, :through => :favorites, :source => :product
  
  def is_fan_of?(group)
   favorite_products.include?(group)
  end

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  ratyrate_rater

  def admin?
    is_admin
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required

   def index
     @products = Product.all
   end

  def new
  @product = Product.new
end

def show
  @product = Product.find(params[:id])
end


def create
  @product = Product.new(product_params)

  if @product.save
    redirect_to admin_products_path
  else
    render :new
  end
end

def edit
   @product = Product.find(params[:id])
 end

 def update
   @product = Product.find(params[:id])

   if @product.update(product_params)
     redirect_to admin_products_path
   else
     render :edit
   end
 end

private

def product_params
  params.require(:product).permit(:title, :description, :quantity, :price, :image, :mu_name, :ci_name, :shi_name, :is_mu, :is_ci, :is_shi)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_action :validates_search_key, only: [:search]
before_action :authenticate_user!, only: [:favorite, :unfavorite]

def favorite
 	@product = Product.find(params[:id])
 		current_user.favorite_products << @product
 		redirect_to :back
    flash[:notice] = "成功将#{@product.title}加入收藏夹"
end

def unfavorite
 	@product = Product.find(params[:id])
 	current_user.favorite_products.delete(@product)
 	redirect_to :back
  flash[:notice] = "已将#{@product.title}从收藏夹取出"
end

def search
  if @query_string.present?
    @products = search_params
  else
    @products = Product.all
  end
end

def index
  @products = Product.all
end

def show
  @product = Product.find(params[:id])
end

def add_to_cart
  @product = Product.find(params[:id])
  if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "成功将#{@product.title}加入购物车"
  else
    flash[:warning] = "你的购物车已有此物品"
  end
    redirect_to :back
end


protected

def validates_search_key
  @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
end

private

def search_params
  Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true)
end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

def render_cart_total_price(cart)

  cart.total_price
end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
 def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <% if @product.image.present? %>
  <span>目前商品图</span> <br>
  <%= image_tag(@product.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <div class="group">
    <%= f.input :is_mu %>
    <%= f.input :is_ci %>
    <%= f.input :is_shi %>
  </div>
  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/admin/products/index.html.erb
<style media="screen">
  .adproducts-index{

  }
</style>


<div class="adproducts-index">
  <h2> Product List </h2>

  <div class="pull-right" style="padding-bottom: 20px;">
    <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th width="220">Product Pic</th>
        <th>Name</th>
        <th>Price</th>
        <th width="100"> Options</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <%= product.id %>
          </td>
          <td>
            <%= link_to product_path(product) do %>
              <% if product.image.present? %>
                <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= product.title %>
          </td>
          <td>
            <%= product.price %>
          </td>
          <td>
            <%= link_to("Edit", edit_admin_product_path(product)) %>
          </td>



        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
  <div class="group">
  <%= f.input :is_mu %>
  <%= f.input :is_ci %>
  <%= f.input :is_shi %>
  </div>
<% end %>

app/views/admin/products/show.html.erb
<h1><%= @product.title %></h1>
<p>
<%= simple_format(@product.description) %>

</p>

app/views/products/_search_bar.html.erb
<style media="screen">
  .eveysearch{
    
    position: absolute;
    z-index: 2;
    top:8px;
    left:350px;
  }

  @media(max-width:820px){
  	.eveysearch{width:50%}

  	}

  	@media(max-width:580px){
  	.eveysearch{width:30%}

  	}

  	@media(max-width:350px){
  .eveysearch{width:20%}

  	}


</style>



<div class="eveysearch">
  <div class="col-md-6">
    <%= form_tag search_products_path, method: :get, class: 'products-search-form'  do %>
      <div class="input-group">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="搜索心仪的家居">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>

app/views/products/index.html.erb
<head>

</head>
<style media="screen">
  .products-evey{
  margin-top: 30px;
margin-left: 40px;
text-decoration: none;
  }
  .productstitle{
    margin-left: 40px;
    margin-bottom: 20px;
  }
  .productimage{
    margin-bottom: 30px;

  }
  .productimage:hover{

  }
  .boxcenter{
    margin: 0 auto;
  }

  #panel, #flip {
    padding: 5px;
    text-align: center;
    //background-color: #d8d6d6;
    background-color: grey;
    border: solid 1px #c3c3c3;
    color:white;
}

#panel {
    padding: 30px;
    display: none;

}
.pdt-index{
  background-image: url("https://ooo.0o0.ooo/2017/02/17/58a693c65a5d8.jpg");
background-size: cover;
margin: 0 auto;

}
.titlebox{
  color:grey;
  height:90px;
  width:210px;
  background-color:white ;
  line-height: 50px;
  clear: both;
  margin-bottom: 50px;
  text-align: center;
  border-radius: 3px;

}
.titlebox:hover{
  background-color:rgba(255,255,255,0.8);
}
.productstitle{
  color: #edeeec;
  text-align:left;
  font-size: 30px;
}
.smallcircle{
  width:50px;
  height:50px;
  background-color: #c5c5c5;
  border-radius: 25px;
  border:2px solid grey;
  margin-bottom: 10px;
  text-align: center;
  line-height: 50px;
  font-size: 25px;
  font-weight: bold;
  position: relative;
}
.smallcircle:hover{
  background-color: orange;
  border: 2px solid white;
  color:white;
}
.qbbb-text{
  font-size:12px;
  color: white;
  position: relative;
  left:20px;
  top:-4px;
}
.nav-left{
  height: 1900px;
  //background-color: yellow;

}
.nav-inside{
  width:90%;
  height:50px;
  background-color: rgba(0,0,0,0.3);
  border-radius: 3px;
  margin-bottom: 5px;
  color: white;
  line-height: 50px;
  text-align: center;
}
.nav-inside:hover{
  background-color: orange;
  border:1px solid white;
  text-decoration: none;
}
.nav-text{
   color:white;
   text-decoration: none;
}
.nav-text:hover{
  color:white;
  text-decoration: none;

}
</style>

<!--扫描二维码-->
<div id="flip">点击扫描二维码，获取更多优惠</div>
<div id="panel">

<img src="https://ooo.0o0.ooo/2017/02/15/58a4053a5d32a.png" alt="">
</div>
<!--扫描二维码结束-->

<body class="pdt-index">




<div class="products-evey">

<!--题头内容开始-->
<div class="qbbb">
  <h2 class="productstitle" style="">全部宝贝</h2>
  <hr>
  <table>
    <tr>
      <td><div class="smallcircle">邮</div></td>
      <td class="qbbb-text">全国包邮
        <br>卖家承担从卖家处发货到您收货地址处的大陆非偏远地区首次发货的运费。</td>

    </tr>

    <tr>
      <td><div class="smallcircle">保</div></td>
      <td class="qbbb-text">退货运费险
<br>卖家承诺提供退货运费险，在交易成功前，消费者发起退货请求，保险公司对退货产生的单程运费提供保险服务。</td>

    </tr>

    <tr>
      <td><div class="smallcircle">发</div></td>
      <td class="qbbb-text">48小时发货
<br>卖家承诺在您付款后的48小时内完成发货，以快递公司系统内揽件记录的时间为准（定制、预售、等特殊类目除外）。</td>

    </tr>

    <tr>
      <td><div class="smallcircle">退</div></td>
      <td class="qbbb-text">质无忧
        <br>商家承诺所售商品如因“不喜欢/不想要/不适合”或质量问题发生退货退款，可向交易诚信记录良好的消费者提供闪电退货和极速退款服务。</td>

    </tr>
  </table>

  <hr>
</div>

<!--题头内容结束-->



<!--产品内容开始-->


<!--左侧导航栏开始-->
<div class="col-xs-6 col-md-3 nav-left">

<div class="nav-text">

     <%= link_to favorites_path, :class => "nav-text" do %>
    <div class="nav-inside">
我的收藏夹 <i class="fa fa-gratipay" aria-hidden="true"></i>
  </div>
<% end %>
</div>


<div class="nav-text">
     <%= link_to carts_path, :class => "nav-text"  do  %>
    <div class="nav-inside">
我的购物车 <i class="fa fa-shopping-cart" aria-hidden="true"></i>
  </div>
<% end %>
</div>


<a class="nav-text" href="products_mu/"><div class="nav-inside">
所有木制品  <i class="fa fa-tree" aria-hidden="true"></i>
  </div></a>
  <a class="nav-text" href="products_ci/"><div class="nav-inside">
所有瓷制品  <i class="fa fa-coffee" aria-hidden="true"></i>
  </div></a>
  <a class="nav-text" href="products_shi/"><div class="nav-inside">
所有の饰品  <i class="fa fa-pagelines" aria-hidden="true"></i>
  </div></a>





</div>
<!--左侧导航栏结束-->





  <% @products.each do |product| %>
  <div class="col-xs-6 col-md-3 boxcenter">


    <%= link_to product_path(product) do %>


    <% if product.image.present? %>


    <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
    <% else %>

      <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>


    <% end %>
    <% end %>
<div class="titlebox">

      【<%= product.title %>】
       <span class="" style="color:orange;font-weight:bold;">¥ <%= product.price %></span>


       <!--收藏开始-->
           <div class="heart-e" style="float:left;position:absolute;top:262px;left:30px;">
             <% if user_signed_in? %>
              <% if !current_user.is_fan_of?(product) %>
                       <%= link_to favorite_product_path(product), :class => "like btn btn-default",method: :post do %>
                       <i class="fa fa-heart" aria-hidden="true"></i>
                       <% end %>
                     <% else %>
                       <%= link_to unfavorite_product_path(product), :class => "like btn btn-default",method: :post do %>
                       <i class="fa fa-heart" aria-hidden="true" style="color:red;"></i>
                      <% end %>
                    <% end %>
                    <% else %>
                       <%= link_to favorite_product_path(product), :class => "like btn btn-default", method: :post do %>
                         <i class="fa fa-heart-o", style="color:red;"></i>
                       <% end %>
                    <% end %>
            </div>
       <!--收藏结束-->

       <!--加入购物车开始-->

           <div style="float:left;position:absolute;top:260px;left:90px;">
           <%= link_to("  加入购物车", add_to_cart_product_path(product), :method => :post, :class => "btn btn-warning fa fa-shopping-cart") %>
           </div>

       <!--加入购物车结束-->



<div class="" style="height:30px;width:100%;">

</div>

    </div>

<!--产品内容结束-->





  </div>

  <% end %>

</div>

<script src="http://www.w3schools.com/lib/w3data.js"></script>
<% yield :handwrite_javascript %>
</body>

<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});





$(".thumbnail").mouseenter(function () {
    $(this).fadeOut(300).fadeIn(100)

})






</script>

app/views/products/search.html.erb
<head>

</head>
<style media="screen">
  .products-evey{
    margin-top: 30px;
margin-left: 40px;
  }
  .productstitle{
    margin-left: 40px;
    margin-bottom: 20px;
  }
  .productimage{
    margin-bottom: 30px;

  }
  .productimage:hover{

  }
  .boxcenter{
    margin: 0 auto;
  }

  #panel, #flip {
    padding: 5px;
    text-align: center;
    //background-color: #d8d6d6;
    background-color: grey;
    border: solid 1px #c3c3c3;
    color:white;
}

#panel {
    padding: 30px;
    display: none;

}
.pdt-index{
  background-image: url(https://ooo.0o0.ooo/2017/02/17/58a693c65a5d8.jpg);
background-size: cover;
margin: 0 auto;

}
.titlebox{
  color:#edeeec;
  height:30px;
  width:210px;
  background-color:rgba(0,0,0,0.3);
  line-height: 30px;
  clear: both;
  margin-bottom: 20px;
  text-align: center;
  border-radius: 3px;
}
.titlebox:hover{
  background-color: #02142e;
}
</style>

<!--扫描二维码-->
<div id="flip">点击扫描二维码，获取更多优惠</div>
<div id="panel">

<img src="https://ooo.0o0.ooo/2017/02/15/58a4053a5d32a.png" alt="">
</div>
<!--扫描二维码结束-->

<body class="pdt-index">


<div class="products-evey">
  <h2 class="productstitle" style="color: #edeeec;">搜索到的宝贝</h2>

<!--产品内容开始-->
  <% @products.each do |product| %>
  <div class="col-xs-6 col-md-3 boxcenter">


    <%= link_to product_path(product) do %>


    <% if product.image.present? %>


    <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
    <% else %>

      <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>


    <% end %>
    <% end %>
<div class="titlebox">

      【<%= product.title %>】
       <span class="" style="color:orange;font-weight:bold;">¥ <%= product.price %></span>

<div class="" style="height:30px;width:100%;">

</div>

    </div>

<!--产品内容结束-->





  </div>

  <% end %>

</div>
  <script src="http://www.w3schools.com/lib/w3data.js"></script>
  <% yield :handwrite_javascript %>

</body>

<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});



</script>

app/views/products/show.html.erb
<style media="screen">
  .productsshow-evey{

padding-left: 40px;
padding-right: 40px;
width: 100%;
background-color: grey;
background-image: url("https://static.pexels.com/photos/4827/nature-forest-trees-fog.jpeg");
background-size: cover;
background-repeat: repeat-y;


  }
  .pdc-description{
    //background-color: rgba(0, 0, 0, 0.3);
    padding-bottom: 10px;
    padding-left: 20px;
    padding-right: 20px;
      padding-top: 30px;
  }
  .reviewbox{
    background-color: rgba(255, 255, 255, 0.8);
    //box-shadow: 1px 1px 1px grey;
    padding-bottom: 30px;

  }
  .heart-e{
    width: 100px;
    height:200px;
  }
</style>
<div class="productsshow-evey">


  <div class="col-md-6" style="padding-top:30px;">
    <% if @product.image.present? %>


    <div id="zoom_01">
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    </div>


    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>

  <div class="col-md-6 pdc-description">
    <h2> <%= @product.title %> </h2>

    <div style="height:100px;">

      <p>
        <%= @product.description %>
      </p >
      <hr>
    </div>
    <div> 数量 : <%= @product.quantity %> </div>
  </br>
    <div>
    外观 : <%= rating_for @product, 'a', disable_after_rate: true %>
    质地 : <%= rating_for @product, 'b', disable_after_rate: true %>
    性价比 : <%= rating_for @product, 'c', disable_after_rate: true %>
    </div>

    <div class="product-price"> ￥ <%= @product.price %> </div>
    <!--收藏开始-->
        <div class="heart-e" style="margin-top:20px;float:left;margin-right:30px;">
          <% if user_signed_in? %>
           <% if !current_user.is_fan_of?(@product) %>
                    <%= link_to favorite_product_path(@product), :class => "like btn btn-default",method: :post do %>
                    <i class="fa fa-heart" aria-hidden="true">    收藏宝贝</i>
                    <% end %>
                  <% else %>
                    <%= link_to unfavorite_product_path(@product), :class => "like btn btn-default",method: :post do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color:red;"></i>
                   <% end %>
                 <% end %>
                 <% else %>
                    <%= link_to favorite_product_path(@product), :class => "like btn btn-default", method: :post do %>
                      <i class="fa fa-heart-o fa-lg", style="color:red;"></i>
                    <% end %>
                 <% end %>
         </div>
    <!--收藏结束-->

<!--加入购物车开始-->
    <div class="pull-right" style="margin-top:10px;">
      <% if @product.quantity > 0 %>
    <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-lg btn-danger") %>
   <% else %>
    已销售一空
   <% end %>

    </div>

<!--加入购物车结束-->

  </div>

  <!--搜索区域开始-->
  <div class="reviewbox row">
    <div class="review">
      <div class="col-sm-10 col-sm-offset-1">
        <h3 class="reviews_title">
          <%= @product.reviews.count %> 评论
        </h3>
        <hr>
        <div id="reivews">
          <%= render @product.reviews%>
          <hr>
          <%= render "reviews/form"%>
        </div>
      </div>
    </div>
  </div>

  <!--搜索区域结束-->
</div>




<script type="text/javascript">
  $('#zoom_01').elevateZoom();
</script>