config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  devise_for :users

  namespace :admin do
    resources :products
    resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end




  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :reviews
  end



  resources :favorites

resources :carts do
  collection do
    delete :clean
    post :checkout
  end
end

namespace :account do
  resources :orders
end

  resources :orders do
    member do
     post :pay_with_alipay
     post :pay_with_wechat
     post :apply_to_cancel
    end
  end






    resources :cart_items
    resources :orders
    resources :products_mu
    resources :products_ci
    resources :products_shi
    resources :protfolio

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product



    def add_product_to_cart(product)
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
      ci.save
    end


def total_price
  sum = 0
  cart_items.each do |cart_item|
    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end
  end
  sum
end


def clean!
  cart_items.destroy_all
end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :product_lists
    before_create :generate_token

    def generate_token
      self.token = SecureRandom.uuid
    end

   def set_payment_with!(method)
    self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  include AASM

  aasm do
   state :order_placed, initial: true
   state :paid
   state :shipping
   state :shipped
   state :order_cancelled
   state :good_returned


  event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
  end

  event :ship do
    transitions from: :paid,         to: :shipping
  end

  event :deliver do
    transitions from: :shipping,     to: :shipped
  end

  event :return_good do
    transitions from: :shipped,      to: :good_returned
  end

  event :cancell_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
  end
end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  ratyrate_rateable "a", "b", "c"

  has_many :reviews

  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user

end

app/models/product_ci.rb
class ProductCi < ApplicationRecord

has_many :reviews

end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/product_mu.rb
class ProductMu < ApplicationRecord

has_many :reviews

end

app/models/product_shi.rb
class ProductShi < ApplicationRecord

has_many :reviews

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :product
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :favorites
  has_many :favorite_products, :through => :favorites, :source => :product
  
  def is_fan_of?(group)
   favorite_products.include?(group)
  end

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  ratyrate_rater

  def admin?
    is_admin
  end

end

app/helpers/carts_helper.rb
module CartsHelper

def render_cart_total_price(cart)

  cart.total_price
end


end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
 def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_floatingbar.html.erb
<style media="screen">
  .floatingevey{
    width: 100%;
    height: 50px;
    background-color: rgba(0,0,0,0.5);
    position: fixed;
    right: 0;
    bottom: 0;
    z-index: 98;
  }
  .backtotop, .fl3{
    color:white;
    font-size: 16px;
    line-height: 50px;
    float: right;
    margin-right: 20px;
  }
  .backtotop:hover{
    color:orange;
  }
  .fl3 a{
    color: white;

  }
.fl3 a:hover{
  color:orange;

}
.othericons{
  position: absolute;
  left:0;
  width:300px;
  height:50px;
  //background-color: yellow;
}
.icooon{
color: white;

}
.icooon:hover{
  color:orange;
}
.ic-1,.ic-2,.ic-3{
  float: left;
  width:20px;
  height:20px;
  margin: 0 auto;
  //background-color: red;
  position: relative;
  top:15px;
  margin-left: 20px;

}
</style>


<div class="floatingevey">

<div class="othericons">
  <div class="ic-1">
    <a href="/" class="icooon"><i class="fa fa-home fa-lg" aria-hidden="true"></i></a>
  </div>
  <div class="ic-2">
    <a href="/favorites" class="icooon"><i class="fa fa-gratipay fa-lg" aria-hidden="true"></i></a>
  </div>
  <div class="ic-3">
  <a href="/carts" class="icooon"><i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></a>
  </div>

  <div class="ic-1">
    <a href="/products_mu" class="icooon"><i class="fa fa-tree fa-lg" aria-hidden="true"></i></a>
  </div>
  <div class="ic-2">
    <a href="/products_ci" class="icooon"><i class="fa fa-coffee fa-lg" aria-hidden="true"></i></a>
  </div>
  <div class="ic-3">
  <a href="/products_shi" class="icooon"><i class="fa fa-pagelines fa-lg" aria-hidden="true"></i></a>
  </div>


</div>




<div class="fl1">


</div>
<div class="fl4">
 <a href="#" class="backtotop">返回顶部</a>

</div>

<div class="fl3">
<a href="https://fullstack.xinshengdaxue.com/works/197"> 支持我们&nbsp;<i class="fa fa-thumbs-o-up" aria-hidden="true"></i></a>
</div>


<div class="fl3">
<a href="Mailto:zhongwen322@gmail.com"> 联系我们&nbsp;<i class="fa fa-envelope-o" aria-hidden="true"></i></a>
</div>

</div>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 0px;">
    <p class="text-center">Copyright ©2017 MJZW
        <br>Designed by LIN MINGJIAN & ZHONG WEN

    </p>
</footer>

app/views/common/_navbar.html.erb
<style media="screen">
body {
font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
font-size:14px;
}

h1 {
margin-top:0px;
margin-bottom:8px;
}
.navbar{
  //position: fixed;
  //top:0;
  //width: 100%;
  //z-index: 98;
}

</style>


<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
<img src="https://ooo.0o0.ooo/2017/02/13/58a0d236d8029.png" width="100" height="30" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav">
            <li class="active">
              <%= link_to("全部商品", products_path) %>
            </li>
            <li class="active">
              <a href="/protfolio">店主画廊</a>
            </li>



          </ul>


              <!--搜索框开始-->

<%= render :partial => "products/search_bar" %>

              <!--搜索框结束-->



            <ul class="nav navbar-nav navbar-right" style="margin-right:30px;margin-top:-8px;">
               <li>

         <%= link_to carts_path do  %>
            购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
         <% end %>
             </li>
             <li>
         <%= link_to favorites_path do  %>
            收藏夹 <i class="fa fa-gratipay" aria-hidden="true"></i>
         <% end %>
       </li>





                  <% if !current_user %>

                  <li><%= link_to("注册", new_user_registration_path, class: 'fa fa-american-sign-language-interpreting') %> </li>

                  <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>



                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">

                      <% if current_user.admin? %>
                               <li>
                                 <%= link_to("   Admin 选单", admin_products_path,class: 'fa fa-user' ) %>
                               </li>
                             <% end %>

                             <li>
                            <%= link_to("   个人订单列表", account_orders_path,class: 'fa fa-list' ) %>
                           </li>


                        <li> <%= link_to(content_tag(:i, '   登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

</nav>